# 第2部　Pythonによる時系列分析の基本

## 第2章　Pythonの基本

### 基本的な演算

In [1]:
# 足し算
1 + 1

2

In [2]:
# 引き算
3 - 1

2

In [3]:
# 掛け算
2 * 3

6

In [4]:
# 割り算
5 / 2

2.5

In [5]:
# 累乗
2 ** 4

16

In [6]:
# やや複雑な計算
2 ** (1 / 2)

1.4142135623730951

### 文字列

In [7]:
'A'

'A'

In [8]:
"A"

'A'

### 変数

#### 変数の基本

In [9]:
x = 5
x

5

In [10]:
x + 3

8

#### 複数の変数の定義

In [11]:
a, b = 1, 2

In [12]:
a

1

In [13]:
b

2

### 関数

#### 関数の作成

In [14]:
def my_func(hikisu):
    return hikisu * 2

In [15]:
my_func(x)

10

#### 頻繁に使う関数

In [16]:
# print関数
print('足し算　1 + 2 = ', 1 + 2)
print('引き算　1 - 2 = ', 1 - 2)

足し算　1 + 2 =  3
引き算　1 - 2 =  -1


In [17]:
# round関数
round(2.345, 2)

2.35

In [18]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



### type関数とdir関数の利用

In [19]:
type('ABC')

str

In [20]:
dir('ABC')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [21]:
'ABC'.lower()

'abc'

In [22]:
help('ABC'.lower)

Help on built-in function lower:

lower() method of builtins.str instance
    Return a copy of the string converted to lowercase.



### list

#### listの基本

In [23]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [24]:
my_list[0]

1

#### listに対する関数の適用

In [25]:
len(my_list)

4

In [26]:
sum(my_list)

10

### 辞書型

In [27]:
my_dict = {
    'A':3,
    'B':7
}
my_dict

{'A': 3, 'B': 7}

In [28]:
my_dict['A']

3

### for構文

In [29]:
for i in range(0, 3):
    print(i)

0
1
2


In [30]:
for i in [1, 3, 5, 7]:
    print(i)

1
3
5
7


### if構文

In [31]:
def check_num(data):
    if(data < 0):
        return '0未満です'
    else:
        return '0以上です'

In [32]:
for i in range(-2, 2):
    print('i =', i, 'の判別結果', check_num(i))

i = -2 の判別結果 0未満です
i = -1 の判別結果 0未満です
i = 0 の判別結果 0以上です
i = 1 の判別結果 0以上です


### numpyの利用

In [33]:
import numpy as np

#### ndarray

In [34]:
my_array = np.array([1,2,3,4])
my_array

array([1, 2, 3, 4])

#### numpyが提供するndarrayを作る関数

In [35]:
np.zeros(4)

array([0., 0., 0., 0.])

In [36]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [37]:
np.arange(0, 0.8, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

#### numpyが提供する関数の利用

In [38]:
np.sum(my_array)

10

In [39]:
np.cumsum(my_array)

array([ 1,  3,  6, 10])

In [40]:
np.log2(my_array)

array([0.       , 1.       , 1.5849625, 2.       ])

In [41]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### pandasの利用

In [42]:
import pandas as pd

#### DataFrame

In [43]:
my_df = pd.DataFrame({
    'A': np.zeros(4), 
    'B': np.log(my_array)
})
print(my_df)

     A         B
0  0.0  0.000000
1  0.0  0.693147
2  0.0  1.098612
3  0.0  1.386294


In [44]:
my_df['B']

0    0.000000
1    0.693147
2    1.098612
3    1.386294
Name: B, dtype: float64

In [45]:
my_df.B

0    0.000000
1    0.693147
2    1.098612
3    1.386294
Name: B, dtype: float64

#### Series

In [46]:
my_series = pd.Series(np.zeros(4))
my_series

0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64

#### indexの設定

In [47]:
my_series.index = np.array([5, 9, 2, 8])
my_series

5    0.0
9    0.0
2    0.0
8    0.0
dtype: float64

#### apply

In [48]:
print(my_df.apply(np.exp))

     A    B
0  1.0  1.0
1  1.0  2.0
2  1.0  3.0
3  1.0  4.0


In [49]:
print(my_df.apply(np.exp).apply(my_func))

     A    B
0  2.0  2.0
1  2.0  4.0
2  2.0  6.0
3  2.0  8.0
